### ISSUE TITLE
Installing Panopuppet without Virtualenv/VirtualEnvWrapper

### ISSUE THREAD

**Issue by lmayorga1980** [propyless/panopuppet#116]
I have the following issue trying to start httpd service

```
[Mon Feb 01 16:28:43 2016] [error] [client ::1] mod_wsgi (pid=4433): Target WSGI
 script '/apps/panopuppet/puppet/wsgi.py' cannot be loaded as Python module.
[Mon Feb 01 16:28:43 2016] [error] [client ::1] mod_wsgi (pid=4433): Exception o
ccurred processing WSGI script '/apps/panopuppet/puppet/wsgi.py'.
[Mon Feb 01 16:28:43 2016] [error] [client ::1] Traceback (most recent call last
):
[Mon Feb 01 16:28:43 2016] [error] [client ::1]   File "/apps/panopuppet/puppet/
wsgi.py", line 12, in <module>
[Mon Feb 01 16:28:43 2016] [error] [client ::1]     from puppet.settings import
BASE_DIR
[Mon Feb 01 16:28:43 2016] [error] [client ::1]   File "/apps/panopuppet/puppet/
settings.py", line 12, in <module>
[Mon Feb 01 16:28:43 2016] [error] [client ::1]     import yaml
[Mon Feb 01 16:28:43 2016] [error] [client ::1]   File "/apps/python/3.5/lib/pyt
hon3.5/site-packages/yaml/__init__.py", line 284
[Mon Feb 01 16:28:43 2016] [error] [client ::1]      class YAMLObject(metaclass=
YAMLObjectMetaclass):
[Mon Feb 01 16:28:43 2016] [error] [client ::1]                                ^

[Mon Feb 01 16:28:43 2016] [error] [client ::1]  SyntaxError: invalid syntax
```

Not a python expert here but according to the httpd.conf there is no place where i can see python3.5 configured.

```
WSGISocketPrefix /var/run/wsgi
<VirtualHost *:80>
    ServerName panupuppet.server
    WSGIDaemonProcess panopuppet user=apache group=apache threads=5 python-path=
/apps/panopuppet:/apps/python/3.5/lib/python3.5/site-packages
    WSGIScriptAlias / /apps/panopuppet/puppet/wsgi.py
    ErrorLog /var/log/httpd/panopuppet.error.log
    CustomLog /var/log/httpd/panopuppet.access.log combined

    Alias /static /srv/staticfiles/
    <Directory /apps/panopuppet>
        Satisfy Any
        Allow from all
    </Directory>

    <Directory /apps/panopuppet/>
        WSGIProcessGroup panopuppet
    </Directory>
</VirtualHost>
```

**Comment by propyless** [comment]
Please confirm that python 3.5 is in the path.
I have not even tested PanoPuppet with version 3.5. I know that 3.4 works.

**Comment by lmayorga1980** [comment]
I just added a symlink to /usr/bin/python3.5 but have the same error.

**Comment by propyless** [comment]
python -c 'import yaml'

does it fail?

**Comment by lmayorga1980** [comment]
actually `python3.5 -c 'import yaml'`

Does not fail.

**Comment by propyless** [comment]
so what does fail?

**Comment by lmayorga1980** [comment]
I wonder if apache is trying to use my default python 2.6 and that is the reason why its failing.

**Comment by propyless** [comment]
You may need to compile wsgi with python 3.5 in that case.

**Comment by propyless** [comment]
https://code.google.com/archive/p/modwsgi/wikis/QuickInstallationGuide.wiki

under the Configuring The Source Code part of the wiki.

Also remove the mod_wsgi package i suppose.

**Comment by sheijmans** [comment]
I thought the default RHEL6 httpd-2.2.15 was for python2.6.
mod_wsgi-3.2-7 also depends on pyhton2.6;
```
rpm -qpR mod_wsgi-3.2-7.el6.x86_64.rpm
...
libpython2.6.so.1.0()(64bit
...
````

**Comment by propyless** [comment]
Yes, this is why in my readme i noted that I used python33-mod_wsgi from the IUS repo.
BUT, I think the IUS repo has been updated recently so I just think installing python 3.x in some way (scl (epel?)) and compiling mod_wsgi yourself is the easiet solution.
`sudo yum install httpd python33-mod_wsgi`

**Comment by propyless** [comment]
Yo,
Did you manage to solve this @lmayorga1980?

**Comment by lmayorga1980** [comment]
I am using a RHEL 7.x and I have the following issue.

```shell
$ sudo /apps/python/3.5/bin/python3.5 manage.py migrate
/apps/panopuppet/pano/urls.py:58: RemovedInDjango110Warning: django.conf.urls.pa
tterns() is deprecated and will be removed in Django 1.10. Update your urlpatter
ns to be a list of django.conf.urls.url() instances instead.
  url(r'^api/dashboard/nodes/$', dashboard_nodes_json, name='api_dashboard_nodes
'),

/apps/python/3.5/lib/python3.5/site-packages/django/template/utils.py:37: Remove
dInDjango110Warning: You haven't defined a TEMPLATES setting. You must do so bef
ore upgrading to Django 1.10. Otherwise Django will be unable to load templates.

  "unable to load templates.", RemovedInDjango110Warning)

/apps/panopuppet/puppet/urls.py:10: RemovedInDjango110Warning: django.conf.urls.
patterns() is deprecated and will be removed in Django 1.10. Update your urlpatt
erns to be a list of django.conf.urls.url() instances instead.
  url(r'^puppetadmin/', include(admin.site.urls)),

System check identified some issues:

WARNINGS:
?: (urls.W001) Your URL pattern '^$' uses include with a regex ending with a '$'
. Remove the dollar from the regex to avoid problems including URLs.
Traceback (most recent call last):
  File "/apps/python/3.5/lib/python3.5/site-packages/django/db/backends/base/bas
e.py", line 199, in ensure_connection
    self.connect()
  File "/apps/python/3.5/lib/python3.5/site-packages/django/db/backends/base/bas
e.py", line 171, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/apps/python/3.5/lib/python3.5/site-packages/django/db/backends/sqlite3/
base.py", line 207, in get_new_connection
    conn = Database.connect(**conn_params)
sqlite3.NotSupportedError: URIs not supported

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/apps/python/3.5/lib/python3.5/site-packages/django/core/management/__in
it__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/apps/python/3.5/lib/python3.5/site-packages/django/core/management/__in
it__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/apps/python/3.5/lib/python3.5/site-packages/django/core/management/base
.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/apps/python/3.5/lib/python3.5/site-packages/django/core/management/base
.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/apps/python/3.5/lib/python3.5/site-packages/django/core/management/comm
ands/migrate.py", line 89, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/apps/python/3.5/lib/python3.5/site-packages/django/db/migrations/execut
or.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/apps/python/3.5/lib/python3.5/site-packages/django/db/migrations/loader
.py", line 49, in __init__
    self.build_graph()
  File "/apps/python/3.5/lib/python3.5/site-packages/django/db/migrations/loader
.py", line 176, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/apps/python/3.5/lib/python3.5/site-packages/django/db/migrations/record
er.py", line 65, in applied_migrations
    self.ensure_schema()
  File "/apps/python/3.5/lib/python3.5/site-packages/django/db/migrations/record
er.py", line 52, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_name
s(self.connection.cursor()):
  File "/apps/python/3.5/lib/python3.5/site-packages/django/db/backends/base/bas
e.py", line 231, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/apps/python/3.5/lib/python3.5/site-packages/django/db/backends/base/bas
e.py", line 204, in _cursor
    self.ensure_connection()
  File "/apps/python/3.5/lib/python3.5/site-packages/django/db/backends/base/bas
e.py", line 199, in ensure_connection
    self.connect()
  File "/apps/python/3.5/lib/python3.5/site-packages/django/db/utils.py", line 9
5, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/apps/python/3.5/lib/python3.5/site-packages/django/utils/six.py", line
685, in reraise
    raise value.with_traceback(tb)
  File "/apps/python/3.5/lib/python3.5/site-packages/django/db/backends/base/bas
e.py", line 199, in ensure_connection
    self.connect()
  File "/apps/python/3.5/lib/python3.5/site-packages/django/db/backends/base/bas
e.py", line 171, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/apps/python/3.5/lib/python3.5/site-packages/django/db/backends/sqlite3/
base.py", line 207, in get_new_connection
    conn = Database.connect(**conn_params)
django.db.utils.NotSupportedError: URIs not supported
```

**Comment by propyless** [comment]
You are probably using a newer version of django of that is supported for panopuppet.
Could you revert to 1.7 or 1.8 and try again please.

//Takeshi

**Comment by propyless** [comment]
No activity for a while..

**Comment by kevincai100** [comment]
> I am using a RHEL 7.x and I have the following issue.
> 
> ```shell
> $ sudo /apps/python/3.5/bin/python3.5 manage.py migrate
> /apps/panopuppet/pano/urls.py:58: RemovedInDjango110Warning: django.conf.urls.pa
> tterns() is deprecated and will be removed in Django 1.10. Update your urlpatter
> ns to be a list of django.conf.urls.url() instances instead.
>   url(r'^api/dashboard/nodes/$', dashboard_nodes_json, name='api_dashboard_nodes
> '),
> 
> /apps/python/3.5/lib/python3.5/site-packages/django/template/utils.py:37: Remove
> dInDjango110Warning: You haven't defined a TEMPLATES setting. You must do so bef
> ore upgrading to Django 1.10. Otherwise Django will be unable to load templates.
> 
>   "unable to load templates.", RemovedInDjango110Warning)
> 
> /apps/panopuppet/puppet/urls.py:10: RemovedInDjango110Warning: django.conf.urls.
> patterns() is deprecated and will be removed in Django 1.10. Update your urlpatt
> erns to be a list of django.conf.urls.url() instances instead.
>   url(r'^puppetadmin/', include(admin.site.urls)),
> 
> System check identified some issues:
> 
> WARNINGS:
> ?: (urls.W001) Your URL pattern '^$' uses include with a regex ending with a '$'
> . Remove the dollar from the regex to avoid problems including URLs.
> Traceback (most recent call last):
>   File "/apps/python/3.5/lib/python3.5/site-packages/django/db/backends/base/bas
> e.py", line 199, in ensure_connection
>     self.connect()
>   File "/apps/python/3.5/lib/python3.5/site-packages/django/db/backends/base/bas
> e.py", line 171, in connect
>     self.connection = self.get_new_connection(conn_params)
>   File "/apps/python/3.5/lib/python3.5/site-packages/django/db/backends/sqlite3/
> base.py", line 207, in get_new_connection
>     conn = Database.connect(**conn_params)
> sqlite3.NotSupportedError: URIs not supported
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "manage.py", line 10, in <module>
>     execute_from_command_line(sys.argv)
>   File "/apps/python/3.5/lib/python3.5/site-packages/django/core/management/__in
> it__.py", line 353, in execute_from_command_line
>     utility.execute()
>   File "/apps/python/3.5/lib/python3.5/site-packages/django/core/management/__in
> it__.py", line 345, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/apps/python/3.5/lib/python3.5/site-packages/django/core/management/base
> .py", line 348, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/apps/python/3.5/lib/python3.5/site-packages/django/core/management/base
> .py", line 399, in execute
>     output = self.handle(*args, **options)
>   File "/apps/python/3.5/lib/python3.5/site-packages/django/core/management/comm
> ands/migrate.py", line 89, in handle
>     executor = MigrationExecutor(connection, self.migration_progress_callback)
>   File "/apps/python/3.5/lib/python3.5/site-packages/django/db/migrations/execut
> or.py", line 20, in __init__
>     self.loader = MigrationLoader(self.connection)
>   File "/apps/python/3.5/lib/python3.5/site-packages/django/db/migrations/loader
> .py", line 49, in __init__
>     self.build_graph()
>   File "/apps/python/3.5/lib/python3.5/site-packages/django/db/migrations/loader
> .py", line 176, in build_graph
>     self.applied_migrations = recorder.applied_migrations()
>   File "/apps/python/3.5/lib/python3.5/site-packages/django/db/migrations/record
> er.py", line 65, in applied_migrations
>     self.ensure_schema()
>   File "/apps/python/3.5/lib/python3.5/site-packages/django/db/migrations/record
> er.py", line 52, in ensure_schema
>     if self.Migration._meta.db_table in self.connection.introspection.table_name
> s(self.connection.cursor()):
>   File "/apps/python/3.5/lib/python3.5/site-packages/django/db/backends/base/bas
> e.py", line 231, in cursor
>     cursor = self.make_debug_cursor(self._cursor())
>   File "/apps/python/3.5/lib/python3.5/site-packages/django/db/backends/base/bas
> e.py", line 204, in _cursor
>     self.ensure_connection()
>   File "/apps/python/3.5/lib/python3.5/site-packages/django/db/backends/base/bas
> e.py", line 199, in ensure_connection
>     self.connect()
>   File "/apps/python/3.5/lib/python3.5/site-packages/django/db/utils.py", line 9
> 5, in __exit__
>     six.reraise(dj_exc_type, dj_exc_value, traceback)
>   File "/apps/python/3.5/lib/python3.5/site-packages/django/utils/six.py", line
> 685, in reraise
>     raise value.with_traceback(tb)
>   File "/apps/python/3.5/lib/python3.5/site-packages/django/db/backends/base/bas
> e.py", line 199, in ensure_connection
>     self.connect()
>   File "/apps/python/3.5/lib/python3.5/site-packages/django/db/backends/base/bas
> e.py", line 171, in connect
>     self.connection = self.get_new_connection(conn_params)
>   File "/apps/python/3.5/lib/python3.5/site-packages/django/db/backends/sqlite3/
> base.py", line 207, in get_new_connection
>     conn = Database.connect(**conn_params)
> django.db.utils.NotSupportedError: URIs not supported
> ```

how did you solve this problem? i have the same problem.

**Comment by lmayorga1980** [comment]
@kevincai100 I stopped using it.
