### ISSUE TITLE
Installation on debian fails

### ISSUE THREAD

**Issue by nemski** [propyless/panopuppet#6]
As pointed out on [reddit](https://www.reddit.com/r/Puppet/comments/31rnrr/i_need_some_more_testers_for_the_puppet_dashboard/cq697su) I was following your installation steps and hit an issue at line 11

```bash
(panopuppet)root@nu-dev:/srv/repo/panopuppet# python3 manage.py collectstatic
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
  File "/root/.virtualenvs/panopuppet/lib/python3.2/site-packages/django/core/management/__init__.py", line 8, in <module>
    from django.apps import apps
ImportError: No module named apps
```

**Comment by propyless** [comment]
Hi, are you using debian6 or 7?

**Comment by propyless** [comment]
Okay, i installed a dev7 server installed all the dependencies and no virtualenv.

So i also installed python3-pip

then i installed all  the python dependencies and then i managed to run collectstatic command without the same problem you received. I did however... come across a problem with the django auth lib for ldap. I tried to run python3.4 instead but then the installation of python-ldap failed so i'm not sure whats going on.

**Comment by nemski** [comment]
Debian 7, using virtualenv. I noticed I'm using python2 pip. I tried with python3 pip and came across the same issue installing django-auth-ldap:

```python
  Running setup.py install for django-auth-ldap
      File "/usr/local/lib/python3.2/dist-packages/django_auth_ldap/config.py", line 108
        def __init__(self, base_dn, scope, filterstr=u'(objectClass=*)'):
                                                                      ^
    SyntaxError: invalid syntax

      File "/usr/local/lib/python3.2/dist-packages/django_auth_ldap/backend.py", line 334
        logger.debug(u"Authentication failed for %s: %s" % (self._username, e))
                                                       ^
    SyntaxError: invalid syntax

      File "/usr/local/lib/python3.2/dist-packages/django_auth_ldap/tests.py", line 97
        dressler = (force_str(u"uid=dreßler,ou=people,o=test"), {
                                                             ^
    SyntaxError: invalid syntax


    no previously-included directories found matching 'docs/build'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '.DS_Store' found anywhere in distribution
    warning: no previously-included files matching '.workon' found anywhere in distribution
```

continuing with the steps results in a failure with collectstatic command which indicates an issue with ldap:

```python
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.2/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.2/dist-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.2/dist-packages/django/conf/__init__.py", line 46, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.2/dist-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.2/dist-packages/django/conf/__init__.py", line 94, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.2/importlib/__init__.py", line 124, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.2/importlib/_bootstrap.py", line 821, in _gcd_import
    loader.load_module(name)
  File "/usr/lib/python3.2/importlib/_bootstrap.py", line 436, in load_module
    return self._load_module(fullname)
  File "/usr/lib/python3.2/importlib/_bootstrap.py", line 141, in decorated
    return fxn(self, module, *args, **kwargs)
  File "/usr/lib/python3.2/importlib/_bootstrap.py", line 342, in _load_module
    exec(code_object, module.__dict__)
  File "/srv/repo/panopuppet/puppet/settings.py", line 88, in <module>
    from django_auth_ldap.config import LDAPSearch, ActiveDirectoryGroupType
  File "/usr/local/lib/python3.2/dist-packages/django_auth_ldap/config.py", line 108
    def __init__(self, base_dn, scope, filterstr=u'(objectClass=*)'):
                                                                  ^
SyntaxError: invalid syntax
```

**Comment by propyless** [comment]
Hi there,

yep thats the exact same issue I am hitting as well.. Right now i'm not sure what to do about it.

I would say that you pull the latest version of master branch and then change the authentication method variable in pano/settings.py from "LDAP" to None.

This will instead load the default authentication method of user/password in panopuppets local DB.

**Comment by propyless** [comment]
i'll close this issue and put up another issue for figuring out whats wrong with ldap on debian
