### ISSUE TITLE
cannot view dashboard/nodes if you have nodes without a stored report

### ISSUE THREAD

**Issue by propyless** [propyless/panopuppet#84]
So I found this bug while testing a test instance of pp.

I set up a puppetserver and puppetdb instance
I ran puppet without reports = puppetdb set in puppet.conf
I then added that line in puppet.conf
and then I checked panopuppet and got server error 500 on the dashboard and nodes pages.

After some troubleshooting I saw noticed that it was failing on the node that did not have a report for the latest run.

So if you were to use.. panopuppet without storing reports in puppetdb you would have a problem.
but hopefully you store all the reports there.

but i'll see if i can fix this in a good way..

**Comment by exodusftw** [comment]
I've noticed similar issues on the 1.0+ releases where there are intermittent 500 errors on the dashboard/nodes pages using Puppet Enterprise. It seems to inconsistently report "cannot connect to PuppetDB" errors, but this differs in that the 'reports = puppetdb' config entry is present on the masters.

Have you seen this elsewhere?

**Comment by propyless** [comment]
Hi thats strange. Its not something I've seen or heard before. However I have not tested pp on a pe instance. Maybe I should set up the pe VM and test it.

You could try enabling debug mode in the config and copy pasting that stack trace after scrubbing anything secret.

Also take a look in the Apache logs for any errors that might've occurred.

Mvh
Takeshi

**Comment by exodusftw** [comment]
this is the stack trace I see in trying to access the dashboard:

```shell
[Tue May 24 22:55:27.851787 2016] [:error] [pid 32764] Internal Server Error: /pano/api/dashboard/
[Tue May 24 22:55:27.851853 2016] [:error] [pid 32764] Traceback (most recent call last):
[Tue May 24 22:55:27.851859 2016] [:error] [pid 32764]   File "/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages/django/core/handlers/base.py", line 132, in get_response
[Tue May 24 22:55:27.851863 2016] [:error] [pid 32764]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Tue May 24 22:55:27.851867 2016] [:error] [pid 32764]   File "/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
[Tue May 24 22:55:27.851870 2016] [:error] [pid 32764]     return view_func(request, *args, **kwargs)
[Tue May 24 22:55:27.851873 2016] [:error] [pid 32764]   File "/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
[Tue May 24 22:55:27.851890 2016] [:error] [pid 32764]     response = view_func(request, *args, **kwargs)
[Tue May 24 22:55:27.851894 2016] [:error] [pid 32764]   File "/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages/panopuppet-1.3-py3.3.egg/panopuppet/pano/views/api/dashboard_data.py", line 445, in dashboard_json
[Tue May 24 22:55:27.851897 2016] [:error] [pid 32764]     context['total_resource'] = total_resources['Value']
[Tue May 24 22:55:27.851903 2016] [:error] [pid 32764] KeyError: 'Value'
[Tue May 24 22:55:27.851912 2016] [:error] [pid 32764]
```

**Comment by propyless** [comment]
Hm, which version of puppetdb are you using?

**Comment by exodusftw** [comment]
4.0.1

**Comment by propyless** [comment]
It'll come soon.. Hopefully by the end of this week. Hang in there...
