### ISSUE TITLE
Failed trying to restart httpd service

### ISSUE THREAD

**Issue by lmayorga1980** [propyless/panopuppet#94]
**OS:** CentOS release 6.7 (Final)

```
[vagrant@localhost repo]$ sudo cat /var/log/httpd/panopuppet.error.log
[Wed Dec 16 22:16:28 2015] [error] [client 10.0.2.2] mod_wsgi (pid=3656): Target WSGI script '/srv/repo/panopuppet/puppet/wsgi.py' cannot be loaded as Python module.
[Wed Dec 16 22:16:28 2015] [error] [client 10.0.2.2] mod_wsgi (pid=3656): Exception occurred processing WSGI script '/srv/repo/panopuppet/puppet/wsgi.py'.
[Wed Dec 16 22:16:28 2015] [error] [client 10.0.2.2] Traceback (most recent call last):
[Wed Dec 16 22:16:28 2015] [error] [client 10.0.2.2]   File "/srv/repo/panopuppet/puppet/wsgi.py", line 18, in <module>
[Wed Dec 16 22:16:28 2015] [error] [client 10.0.2.2]     from django.core.wsgi import get_wsgi_application
[Wed Dec 16 22:16:28 2015] [error] [client 10.0.2.2]   File "/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages/django/core/wsgi.py", line 2, in <module>
[Wed Dec 16 22:16:28 2015] [error] [client 10.0.2.2]     from django.core.handlers.wsgi import WSGIHandler
[Wed Dec 16 22:16:28 2015] [error] [client 10.0.2.2]   File "/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages/django/core/handlers/wsgi.py", line 10, in <module>
[Wed Dec 16 22:16:28 2015] [error] [client 10.0.2.2]     from django import http
[Wed Dec 16 22:16:28 2015] [error] [client 10.0.2.2]   File "/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages/django/http/__init__.py", line 2, in <module>
[Wed Dec 16 22:16:28 2015] [error] [client 10.0.2.2]     from django.http.request import (
[Wed Dec 16 22:16:28 2015] [error] [client 10.0.2.2]   File "/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages/django/http/request.py", line 10, in <module>
[Wed Dec 16 22:16:28 2015] [error] [client 10.0.2.2]     from django.core import signing
[Wed Dec 16 22:16:28 2015] [error] [client 10.0.2.2]   File "/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages/django/core/signing.py", line 51, in <module>
[Wed Dec 16 22:16:28 2015] [error] [client 10.0.2.2]     from django.utils.module_loading import import_string
[Wed Dec 16 22:16:28 2015] [error] [client 10.0.2.2]   File "/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages/django/utils/module_loading.py", line 67, in <module>
[Wed Dec 16 22:16:28 2015] [error] [client 10.0.2.2]     from importlib.util import find_spec as importlib_find
[Wed Dec 16 22:16:28 2015] [error] [client 10.0.2.2] ImportError: cannot import name find_spec
[Wed Dec 16 22:16:28 2015] [error] [client 10.0.2.2] mod_wsgi (pid=3656): Target WSGI script '/srv/repo/panopuppet/puppet/wsgi.py' cannot be loaded as Python module.
[Wed Dec 16 22:16:28 2015] [error] [client 10.0.2.2] mod_wsgi (pid=3656): Exception occurred processing WSGI script '/srv/repo/panopuppet/puppet/wsgi.py'.
[Wed Dec 16 22:16:28 2015] [error] [client 10.0.2.2] Traceback (most recent call last):
[Wed Dec 16 22:16:28 2015] [error] [client 10.0.2.2]   File "/srv/repo/panopuppet/puppet/wsgi.py", line 18, in <module>
[Wed Dec 16 22:16:28 2015] [error] [client 10.0.2.2]     from django.core.wsgi import get_wsgi_application
[Wed Dec 16 22:16:28 2015] [error] [client 10.0.2.2]   File "/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages/django/core/wsgi.py", line 2, in <module>
[Wed Dec 16 22:16:28 2015] [error] [client 10.0.2.2]     from django.core.handlers.wsgi import WSGIHandler
[Wed Dec 16 22:16:28 2015] [error] [client 10.0.2.2]   File "/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages/django/core/handlers/wsgi.py", line 10, in <module>
[Wed Dec 16 22:16:28 2015] [error] [client 10.0.2.2]     from django import http
[Wed Dec 16 22:16:28 2015] [error] [client 10.0.2.2]   File "/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages/django/http/__init__.py", line 2, in <module>
[Wed Dec 16 22:16:28 2015] [error] [client 10.0.2.2]     from django.http.request import (
[Wed Dec 16 22:16:28 2015] [error] [client 10.0.2.2]   File "/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages/django/http/request.py", line 10, in <module>
[Wed Dec 16 22:16:28 2015] [error] [client 10.0.2.2]     from django.core import signing
[Wed Dec 16 22:16:28 2015] [error] [client 10.0.2.2]   File "/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages/django/core/signing.py", line 51, in <module>
[Wed Dec 16 22:16:28 2015] [error] [client 10.0.2.2]     from django.utils.module_loading import import_string
[Wed Dec 16 22:16:28 2015] [error] [client 10.0.2.2]   File "/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages/django/utils/module_loading.py", line 67, in <module>
[Wed Dec 16 22:16:28 2015] [error] [client 10.0.2.2]     from importlib.util import find_spec as importlib_find
[Wed Dec 16 22:16:28 2015] [error] [client 10.0.2.2] ImportError: cannot import name find_spec
```

**Comment by propyless** [comment]
Hi there!

Thanks for reporting the issue!

Seems to be that Django from release 1.8 has dropped support for Python 3.2 and 3.3.

You can read more here: https://code.djangoproject.com/ticket/25868
