### ISSUE TITLE
Error Step 11 (Centos/RHEL 6)

### ISSUE THREAD

**Issue by lmayorga1980** [propyless/panopuppet#95]
**Python** 3.3.6

`11. Populate the /srv/staticfiles with the staticfiles $ cd /srv/repo/panopuppet $ python manage.py collectstatic Say yes to the question it might ask about overwriting files in the /srv/collectstatic folder.`

```
python manage.py collectstatic
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
  File "/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages/django/core/management/__init__.py", line 10, in <module>
    from django.apps import apps
  File "/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages/django/apps/__init__.py", line 1, in <module>
    from .config import AppConfig
  File "/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages/django/apps/config.py", line 6, in <module>
    from django.utils.module_loading import module_has_submodule
  File "/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages/django/utils/module_loading.py", line 67, in <module>
    from importlib.util import find_spec as importlib_find
ImportError: cannot import name find_spec
```

All the previous steps were executed successfully.

**Comment by propyless** [comment]
Hi!

Seems to be the same underlying issue here as well.
https://code.djangoproject.com/ticket/25868

**Comment by lmayorga1980** [comment]
This is interesting. I tried using `pip install Django==1.9` and `Python 3.3.6`. I guess I will have to downgrade.

**Comment by lmayorga1980** [comment]
I guess you can replace `pip install Django==1.7` on the **requirements.txt**
