### ISSUE TITLE
Step 13 (CentOS 6) Fails

### ISSUE THREAD

**Issue by lmayorga1980** [propyless/panopuppet#96]
I have the following issue trying to execute step #13 

Python: 3.3.6
Django: 1.7

Note: Does this depend on the config.yaml?

```
python manage.py migrate
Traceback (most recent call last):
  File "/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages/django/db/backends/__init__.py", line 133, in ensure_connection
    self.connect()
  File "/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages/django/db/backends/__init__.py", line 122, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages/django/db/backends/sqlite3/base.py", line 374, in get_new_connection
    conn = Database.connect(**conn_params)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages/django/core/management/commands/migrate.py", line 63, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages/django/db/migrations/executor.py", line 17, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages/django/db/migrations/loader.py", line 48, in __init__
    self.build_graph()
  File "/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages/django/db/migrations/loader.py", line 179, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages/django/db/migrations/recorder.py", line 59, in applied_migrations
    self.ensure_schema()
  File "/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages/django/db/migrations/recorder.py", line 49, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.get_table_list(self.connection.cursor()):
  File "/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages/django/db/backends/__init__.py", line 165, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages/django/db/backends/__init__.py", line 138, in _cursor
    self.ensure_connection()
  File "/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages/django/db/backends/__init__.py", line 133, in ensure_connection
    self.connect()
  File "/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages/django/utils/six.py", line 549, in reraise
    raise value.with_traceback(tb)
  File "/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages/django/db/backends/__init__.py", line 133, in ensure_connection
    self.connect()
  File "/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages/django/db/backends/__init__.py", line 122, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/srv/.virtualenvs/panopuppet/lib/python3.3/site-packages/django/db/backends/sqlite3/base.py", line 374, in get_new_connection
    conn = Database.connect(**conn_params)
```

**Comment by propyless** [comment]
Hi,

No the error seems to depend on `sqlite3.OperationalError: unable to open database file`

you'll have to set the correct owner/group permissions on the panopuppet directory so that apache is able to read and modify the database.

**Comment by propyless** [comment]
Hm, i see you havent even started apache yet..
Sorry, OK, hm which user are you running the python manage.py migrate command as?

**Comment by propyless** [comment]
I'm currently available on IRC if you want realtime support

**Comment by lmayorga1980** [comment]
apache is the owner of everything under /srv dirs.

**Comment by propyless** [comment]
is your cwd the panopuppet directory?

**Comment by propyless** [comment]
problem solved:
user running as user that didnt have permissions for panopuppet directory.
